version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: rag_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "rag_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  ollama_ai:
    image: ollama/ollama
    container_name: local_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    # Để cài model tự động, vào CLI của docker: docker exec -it local_ollama ollama run qwen:0.5b

  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql_data:
  ollama_data:
